[project]
name = "stackcompute"
description = "StackCompute - Verifiable compute bounties on Stacks"
authors = []
telemetry = false

[settings]
default_network = "devnet"

[networks.devnet]
settings_file = "settings/Devnet.toml"

[contracts.job-registry]
path = "contracts/job-registry.clar"

[contracts.trophy-sbt]
path = "contracts/trophy-sbt.clar"
depends_on = []

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false